### ISSUE TITLE
To translate documentation in English

### ISSUE THREAD

**Issue by alex-87** [alex-87/HyperGraphLib#2]
To translate documentation in English

**Comment by aquemy** [comment]
Small error in the repository description:

> C++ Hypergraph ~~modelisation~~ modeling Library

Possibly, model**l**ing if you prefer UK english.

I post here because I guess it is a translation mistake from french _modélisation_.

**Comment by alex-87** [comment]
Thank you very much for your help, I modify the repository description. This is exactly a translation mistake from french word, well seen 👍
